name       : perl-sub-uplevel
version    : 0.28
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Sub-Uplevel-0.2800.tar.gz : b4f3f63b80f680a421332d8851ddbe5a8e72fcaa74d5d1d98f3c8cc4a3ece293
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Sub::Uplevel - apparently run a function in a higher stack frame
description: |
    Like Tcl's uplevel() function, but not quite so dangerous. The idea is just to fool caller(). All the really naughty bits of Tcl's uplevel() are avoided.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
